### ISSUE TITLE
The sample app provided with this repo is not building 

### ISSUE THREAD

**Issue by kalyanpgn** [contentful/rich-text-renderer.swift#23]
Hi All, I need some help to render rich text in iOS. I cloned this repo - https://github.com/contentful-labs/rich-text-renderer.swift and did a pod install and tried to run the example project. But the project is not building.

Im getting the error "Cannot find 'calculatePreferredContentSize' in scope" inside the RichTextRenderer library

Also i just cloned the master branch let me know if i do something wrong here. Thanks

**Comment by mariuskatcontentful** [comment]
@kalyanpgn Thank you for catching this. Fixed. Will deploy the fix shortly

**Comment by mariuskatcontentful** [comment]
@kalyanpgn should be sorted in the latest release as well as cocoapods update
