### ISSUE TITLE
Getting a RichTextDocument from plain dictionary data (not fetched with Contentful SDK)

### ISSUE THREAD

**Issue by gchiacchio** [contentful/rich-text-renderer.swift#26]
I'm trying to use this library to render rich text from Contentful, but client side, I'm not using the Contentful SDK for retrieving data, instead I'm using Apollo reaching our own graphql server (Hasura with Contentful integration). Because of that, I'm receiving the content as a swift dictionary (`[String: Any?]`), and I wonder how to create the `RichTextDocument` from it.
Could you give me some directions here?

**Comment by mariuskatcontentful** [comment]
I do not think that the library was designed just to cherry pick stuff from it. But your best and probably the only way in the current state would be to parse the dictionary you receive into a json string and then decode that into the object. Here is a generic example:

let richTextDocumentDictionary: [String: Any?] = <what you get from api>
let encoder = JSONEncoder()
if let jsonData = try? encoder.encode(dic) {
    if let jsonString = String(data: jsonData, encoding: .utf8) {
        // You got that into the string json
        // Now lets encode that into the object of rich text document
        let jsonData = jsonString.data(using: .utf8)!
        let richTextDocument = try! JSONDecoder().decode(RichTextDocument.self, from: jsonData)
    }
}

**Comment by gchiacchio** [comment]
Thanks it's working that way!
