### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by jgallantgs** [contentful/rich-text-renderer.swift#65]
Hi, can you please add support for Swift Package Manager and include the installations instructions in the .readme?

**Comment by PiotrBogus** [comment]
add to your dependencies inside package file
`.package(url: "https://github.com/contentful/rich-text-renderer.swift", .upToNextMajor(from: "0.4.0"))
`then to target
`                .product(name: "ContentfulRichTextRenderer", package: "rich-text-renderer.swift")
`
