### ISSUE TITLE
SimpleTableView does not import UIKit which causes build issues

### ISSUE THREAD

**Issue by dapperchris** [contentful/rich-text-renderer.swift#79]
### Description

When compiling, Xcode can't build because `import UIKit` is missing from the file `SimpleTableView.swift`. The fix is to simply add the import statement to the file. Please see the screenshot below. 

### Steps to reproduce
- Integrate the project 
- Build

### Actual Results
- Xcode can't build the project

### Expected Results
- Xcode can build the project

### Reproduced Using

rich-text-renderer.swift: version 0.4.3 using SPM
Simulator: iPhone 16 Pro
OS: iOS 18.1
Xcode: 16.1
macOS: Sequoia 15.2

### Screenshots

<img width="1512" alt="Screenshot" src="https://github.com/user-attachments/assets/de35d1b1-698c-40c7-8704-4d09c4096171" />

**Comment by mariuskatcontentful** [comment]
Sorry about tht - fixed in latest release https://github.com/contentful/rich-text-renderer.swift/releases/tag/0.4.4
